-- ==================================================================
--  Exercice 12 · Question 5 — Nouvelle colonne
-- ==================================================================
--  Ajoute une colonne telephone (texte) à la table clients
--  existante.
--
--  ✍️  Écris ta requête SQL SOUS ce cadre, enregistre (Ctrl+S),
--      puis vérifie depuis la racine du projet LearnSQL :
--        python3 verifier.py 12 5
-- ==================================================================

