-- ==================================================================
--  Exercice 10 · Question 6 — Les lecteurs
-- ==================================================================
--  Affiche le prénom et le nom des clients qui ont commandé au
--  moins un produit de la catégorie Livres. Chaque client ne doit
--  apparaître qu'une seule fois.
--
--  ✍️  Écris ta requête SQL SOUS ce cadre, enregistre (Ctrl+S),
--      puis vérifie depuis la racine du projet LearnSQL :
--        python3 verifier.py 10 6
-- ==================================================================

