-- ==================================================================
--  Exercice 03 · Question 2 — Budget moyen
-- ==================================================================
--  Affiche le nom et le prix des produits dont le prix est
--  compris entre 20 et 40 € (bornes incluses).
--
--  ✍️  Écris ta requête SQL SOUS ce cadre, enregistre (Ctrl+S),
--      puis vérifie depuis la racine du projet LearnSQL :
--        python3 verifier.py 3 2
-- ==================================================================

